In [5]:
import pandas as pd
import numpy as np

# Cleaning the dataset 'clubs'

In [6]:
club_df = pd.read_csv('./data/clubs.csv')
club_df.head()

,club_id,club_code,name,domestic_competition_id,total_market_value,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,stadium_seats,net_transfer_record,coach_name,last_season,url
0,105,sv-darmstadt-98,Sportverein Darmstadt 1898 e. V.,L1,NaN,30,26.4,11,36.7,1,Merck-Stadion am Böllenfalltor,17810,€-1.60m,NaN,2023,https://www.transfermarkt.co.uk/sv-darmstadt-9...
1,11127,ural-ekaterinburg,FK Ural Yekaterinburg,RU1,NaN,25,28.2,13,52.0,5,Yekaterinburg Arena,23000,€-770k,NaN,2023,https://www.transfermarkt.co.uk/ural-ekaterinb...
2,114,besiktas-istanbul,Beşiktaş Jimnastik Kulübü,TR1,NaN,32,27.4,16,50.0,13,Tüpraş Stadyumu,42590,€-14.50m,NaN,2023,https://www.transfermarkt.co.uk/besiktas-istan...
3,12,as-rom,Associazione Sportiva Roma,IT1,NaN,26,27.4,17,65.4,17,Olimpico di Roma,73261,+€65.20m,NaN,2023,https://www.transfermarkt.co.uk/as-rom/startse...
4,148,tottenham-hotspur,Tottenham Hotspur Football Club,GB1,NaN,29,26.2,21,72.4,22,Tottenham Hotspur Stadium,62062,€-130.40m,NaN,2023,https://www.transfermarkt.co.uk/tottenham-hots...

In [7]:
club_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 426 entries, 0 to 425
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   club_id                  426 non-null    int64
 1   club_code                426 non-null    object
 2   name                     426 non-null    object
 3   domestic_competition_id  426 non-null    object
 4   total_market_value       0 non-null      float64
 5   squad_size               426 non-null    int64
 6   average_age              388 non-null    float64
 7   foreigners_number        426 non-null    int64
 8   foreigners_percentage    379 non-null    float64
 9   national_team_players    426 non-null    int64
 10  stadium_name             426 non-null    object
 11  stadium_seats            426 non-null    int64
 12  net_transfer_record      426 non-null    object
 13  coach_name               0 non-null      float64
 14  last_season              426 non-null    int64
 15  url                      426 non-null    object
dtypes: float64(4), int64(6), object(6)
memory usage: 53.4+ KB

In [8]:
club_df['average_age'].mean()

25.704639175257736

In [9]:
# togliamo le colonne inutili
club_df = club_df.drop(columns=['total_market_value', 'coach_name', 'url'])

# i valori mancanti di average_age sono riempiti con -1
club_df['average_age'] = club_df['average_age'].fillna(-1)

In [10]:
club_df[club_df['squad_size'] == 0].shape[0]

38

In [11]:
# Calcola la percentuale di giocatori stranieri considerando il caso di squad_size zero
club_df['foreigners_percentage'] = np.where(
    club_df['squad_size'] > 0,
    ((club_df['foreigners_number'] * 100) / club_df['squad_size']).round(1),
    0
)

# Mostra il risultato aggiornato
print(club_df[['foreigners_number', 'squad_size', 'foreigners_percentage']])

     foreigners_number  squad_size  foreigners_percentage
0                   11          30                   36.7
1                   13          25                   52.0
2                   16          32                   50.0
3                   17          26                   65.4
4                   21          29                   72.4
..                 ...         ...                    ...
421                  5          30                   16.7
422                 14          29                   48.3
423                 17          25                   68.0
424                 17          26                   65.4
425                  8          25                   32.0

[426 rows x 3 columns]

In [12]:
club_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 426 entries, 0 to 425
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   club_id                  426 non-null    int64
 1   club_code                426 non-null    object
 2   name                     426 non-null    object
 3   domestic_competition_id  426 non-null    object
 4   squad_size               426 non-null    int64
 5   average_age              426 non-null    float64
 6   foreigners_number        426 non-null    int64
 7   foreigners_percentage    426 non-null    float64
 8   national_team_players    426 non-null    int64
 9   stadium_name             426 non-null    object
 10  stadium_seats            426 non-null    int64
 11  net_transfer_record      426 non-null    object
 12  last_season              426 non-null    int64
dtypes: float64(2), int64(6), object(5)
memory usage: 43.4+ KB

In [13]:
# convertiamo il campo net_transfert_record in un valore numerico
import re
def convert_currency_to_float(currency_str):
    if isinstance(currency_str, str):
        # Rimuovere il simbolo di euro e spazi aggiuntivi
        currency_str = currency_str.replace('€', '').strip()
        
        # Determinare il segno del numero
        sign = -1 if currency_str.startswith('-') else 1
        
        # Rimuovere segni di più e di meno per evitare conversioni errate
        currency_str = re.sub(r'[+-]', '', currency_str).strip()
        
        # Convertire milioni (m) e migliaia (k) in numeri float
        num = float(re.sub(r'[km]', '', currency_str))
        if 'm' in currency_str:
            num *= 1000000
        elif 'k' in currency_str:
            num *= 1000
            
        return sign * num
    return currency_str

club_df['net_transfer_record'] = club_df['net_transfer_record'].apply(convert_currency_to_float)

In [14]:
club_df

,club_id,club_code,name,domestic_competition_id,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,stadium_seats,net_transfer_record,last_season
0,105,sv-darmstadt-98,Sportverein Darmstadt 1898 e. V.,L1,30,26.4,11,36.7,1,Merck-Stadion am Böllenfalltor,17810,-1600000.0,2023
1,11127,ural-ekaterinburg,FK Ural Yekaterinburg,RU1,25,28.2,13,52.0,5,Yekaterinburg Arena,23000,-770000.0,2023
2,114,besiktas-istanbul,Beşiktaş Jimnastik Kulübü,TR1,32,27.4,16,50.0,13,Tüpraş Stadyumu,42590,-14500000.0,2023
3,12,as-rom,Associazione Sportiva Roma,IT1,26,27.4,17,65.4,17,Olimpico di Roma,73261,65200000.0,2023
4,148,tottenham-hotspur,Tottenham Hotspur Football Club,GB1,29,26.2,21,72.4,22,Tottenham Hotspur Stadium,62062,-130400000.0,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...
421,68608,cf-os-belenenses,CF Os Belenenses,PO1,30,25.7,5,16.7,0,Estádio do Restelo,19980,0.0,2017
422,724,fc-volendam,Football Club Volendam,NL1,29,22.8,14,48.3,3,Kras Stadion,7384,1800000.0,2023
423,800,atalanta-bergamo,Atalanta Bergamasca Calcio S.p.a.,IT1,25,27.2,17,68.0,15,Gewiss Stadium,21747,87000000.0,2023
424,979,moreirense-fc,Moreirense Futebol Clube,PO1,26,26.0,17,65.4,2,Estádio C. J. de Almeida Freitas,6153,-2050000.0,2023
425,984,west-bromwich-albion,West Bromwich Albion,GB1,25,27.8,8,32.0,4,The Hawthorns,26850,-1350000.0,2020

In [15]:
# Verifica dei record duplicati nel dataset
duplicates_count = club_df.duplicated().sum()

# Mostrare il numero di duplicati trovati
duplicates_count

0

In [16]:
#Controllare che non ci siano stadi con dimensione negativa
negative_stadium_capacity = club_df[club_df['stadium_seats'] < 0]
negative_stadium_capacity.shape[0]

0

In [17]:
# Controllare che la dimensione massima dello stadio sia un valore sensato
max_stadium_capacity = club_df['stadium_seats'].max()
max_stadium_capacity

81365

In [18]:
# Verificare che il numero dei giocatori stranieri sia minore del numero totale di giocatori nella squadra
invalid_foreigners = club_df[club_df['foreigners_number'] > club_df['squad_size']]
invalid_foreigners.shape[0]

0

In [19]:
# Verificare che il numero di giocatori in nazionale sia minore del numero totale di giocatori nella squadra
invalid_nationals = club_df[club_df['national_team_players'] > club_df['squad_size']]
invalid_nationals.shape[0]

0

In [20]:
# Verificare che la last season sia compresa tra il 2012 e il 2023
invalid_seasons = club_df[(club_df['last_season'] < 2012) | (club_df['last_season'] > 2023)]
invalid_seasons.shape[0]

0

In [21]:
club_df.to_csv('./data_cleaned/clubs.csv', index=False)

# Cleaning the dataset 'players'

In [22]:
players_df = pd.read_csv('./data/players.csv')
players_df.head()

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,foot,height_in_cm,market_value_in_eur,highest_market_value_in_eur,contract_expiration_date,agent_name,image_url,url,current_club_domestic_competition_id,current_club_name
0,598,Timo,Hildebrand,Timo Hildebrand,2014,24,timo-hildebrand,Germany,Worms,Germany,...,NaN,NaN,NaN,10000000.0,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/timo-hildebran...,L1,Eintracht Frankfurt
1,670,Martin,Petrov,Martin Petrov,2012,714,martin-petrov,Bulgaria,Vratsa,Bulgaria,...,NaN,NaN,NaN,12000000.0,NaN,IFM,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/martin-petrov/...,ES1,RCD Espanyol Barcelona
2,1323,Martin,Amedick,Martin Amedick,2012,24,martin-amedick,Germany,Paderborn,Germany,...,NaN,NaN,NaN,2750000.0,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/martin-amedick...,L1,Eintracht Frankfurt
3,3195,Jermaine,Pennant,Jermaine Pennant,2013,512,jermaine-pennant,England,Nottingham,England,...,right,173.0,NaN,10500000.0,NaN,Andrew Sky,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/jermaine-penna...,GB1,Stoke City
4,3259,Damien,Duff,Damien Duff,2013,931,damien-duff,Ireland,Ballyboden,Ireland,...,left,177.0,NaN,17000000.0,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/damien-duff/pr...,GB1,Fulham FC

In [23]:
players_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30302 entries, 0 to 30301
Data columns (total 23 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   player_id                             30302 non-null  int64
 1   first_name                            28337 non-null  object
 2   last_name                             30302 non-null  object
 3   name                                  30302 non-null  object
 4   last_season                           30302 non-null  int64
 5   current_club_id                       30302 non-null  int64
 6   player_code                           30302 non-null  object
 7   country_of_birth                      27613 non-null  object
 8   city_of_birth                         28099 non-null  object
 9   country_of_citizenship                29759 non-null  object
 10  date_of_birth                         30255 non-null  object
 11  sub_position                          30130 non-null  object
 12  position                              30302 non-null  object
 13  foot                                  27913 non-null  object
 14  height_in_cm                          28204 non-null  float64
 15  market_value_in_eur                   19383 non-null  float64
 16  highest_market_value_in_eur           28981 non-null  float64
 17  contract_expiration_date              18835 non-null  object
 18  agent_name                            14941 non-null  object
 19  image_url                             30302 non-null  object
 20  url                                   30302 non-null  object
 21  current_club_domestic_competition_id  30302 non-null  object
 22  current_club_name                     30302 non-null  object
dtypes: float64(3), int64(3), object(17)
memory usage: 5.3+ MB

In [24]:
# Rimuoviamo le colonne specificate in quanto irrilevanti
columns_to_remove = ['image_url', 'url', 'first_name', 'last_name', 'highest_market_value_in_eur']
players_df = players_df.drop(columns=columns_to_remove)

In [25]:
players_df.head()

,player_id,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,date_of_birth,sub_position,position,foot,height_in_cm,market_value_in_eur,contract_expiration_date,agent_name,current_club_domestic_competition_id,current_club_name
0,598,Timo Hildebrand,2014,24,timo-hildebrand,Germany,Worms,Germany,1979-04-05,Goalkeeper,Goalkeeper,NaN,NaN,NaN,NaN,NaN,L1,Eintracht Frankfurt
1,670,Martin Petrov,2012,714,martin-petrov,Bulgaria,Vratsa,Bulgaria,1979-01-15,Left Winger,Attack,NaN,NaN,NaN,NaN,IFM,ES1,RCD Espanyol Barcelona
2,1323,Martin Amedick,2012,24,martin-amedick,Germany,Paderborn,Germany,1982-09-06,Centre-Back,Defender,NaN,NaN,NaN,NaN,NaN,L1,Eintracht Frankfurt
3,3195,Jermaine Pennant,2013,512,jermaine-pennant,England,Nottingham,England,1983-01-15,Right Winger,Attack,right,173.0,NaN,NaN,Andrew Sky,GB1,Stoke City
4,3259,Damien Duff,2013,931,damien-duff,Ireland,Ballyboden,Ireland,1979-03-02,Right Midfield,Midfield,left,177.0,NaN,NaN,NaN,GB1,Fulham FC

In [26]:
# Calcoliamo la percentuale di valori mancanti per ogni colonna
missing_data = players_df.isnull().mean() * 100

# Visualizziamo le percentuali di dati mancanti
missing_data.sort_values(ascending=False)

agent_name                              50.693024
contract_expiration_date                37.842387
market_value_in_eur                     36.033925
country_of_birth                         8.874002
foot                                     7.883968
city_of_birth                            7.270147
height_in_cm                             6.923635
country_of_citizenship                   1.791961
sub_position                             0.567619
date_of_birth                            0.155105
current_club_domestic_competition_id     0.000000
player_id                                0.000000
position                                 0.000000
name                                     0.000000
player_code                              0.000000
current_club_id                          0.000000
last_season                              0.000000
current_club_name                        0.000000
dtype: float64

In [27]:
# Impostiamo 'unknown' per i valori delle seguenti colonne:

players_df['agent_name'] = players_df['agent_name'].fillna('unknown')
players_df['country_of_birth'] = players_df['country_of_birth'].fillna('unknown')
players_df['city_of_birth'] = players_df['city_of_birth'].fillna('unknown')
players_df['country_of_citizenship'] = players_df['country_of_citizenship'].fillna('unknown')
players_df['sub_position'] = players_df['sub_position'].fillna('unknown')

In [28]:
# inseriamo -1 nelle seguenti colonne per indicare che non hanno valori di mercato:
market_value_mean = players_df['market_value_in_eur'].mean()
players_df['market_value_in_eur'] = players_df['market_value_in_eur'].fillna(market_value_mean)

In [29]:
# Calcoliamo le statistiche descrittive per alcune colonne numeriche rilevanti
stats = players_df['height_in_cm'].describe()

# Visualizziamo le statistiche per valutare la presenza di outlier
stats

count    28204.000000
mean       182.234577
std          6.833916
min         18.000000
25%        178.000000
50%        182.000000
75%        187.000000
max        207.000000
Name: height_in_cm, dtype: float64

In [30]:
# Calcoliamo la mediana delle altezze, che useremo per sostituire il valore errato
height_median = players_df['height_in_cm'].median()

# Sostituiamo i valori errati di altezza (molto bassi, es. < 100 cm) con la mediana
players_df.loc[players_df['height_in_cm'] < 100, 'height_in_cm'] = height_median

In [31]:
# Calcoliamo la mediana dell'altezza per ogni posizione
median_height_by_position = players_df.groupby('position')['height_in_cm'].median()

# Visualizziamo la mediana dell'altezza per ciascuna posizione
median_height_by_position

position
Attack        180.0
Defender      184.0
Goalkeeper    189.0
Midfield      180.0
Missing       180.0
Name: height_in_cm, dtype: float64

In [32]:
# Imputiamo i valori mancanti di 'height_in_cm' basandoci sulla mediana della loro posizione
players_df['height_in_cm'] = players_df.groupby('position')['height_in_cm'].transform(lambda x: x.fillna(x.median()))

# Verifichiamo nuovamente la presenza di valori mancanti in 'height_in_cm' per assicurarci che siano stati tutti imputati
players_df['height_in_cm'].isnull().sum()

0

In [33]:
# Visualizziamo i valori unici per alcune colonne categoriche per identificare incoerenze
unique_countries = players_df['country_of_birth'].unique()
unique_cities = players_df['city_of_birth'].unique()
unique_foot = players_df['foot'].unique()

unique_countries, unique_cities, unique_foot

(array(['Germany', 'Bulgaria', 'England', 'Ireland', 'Australia',
        'Netherlands', 'Belgium', 'Scotland', 'Senegal', 'Cameroon',
        'France', 'Réunion', 'Uruguay', 'Italy', 'Brazil', 'CSSR',
        'Argentina', 'Turkey', 'Spain', 'Portugal', "Cote d'Ivoire",
        'Northern Ireland', 'Greece', 'Mali', 'Jugoslawien (SFR)', 'UdSSR',
        'unknown', 'Denmark', 'Poland', 'Hungary', 'Sierra Leone',
        'Norway', 'Nigeria', 'Ghana', 'Cape Verde', 'Morocco', 'Romania',
        'East Germany (GDR)', 'Finland', 'Martinique', 'Iran', 'Zaire',
        'Monaco', 'Israel', 'Zimbabwe', 'Paraguay', 'Sweden',
        'New Zealand', 'Yugoslavia (Republic)', 'Austria', 'Switzerland',
        'Burkina Faso', 'Ukraine', 'Canada', 'Iceland', 'Colombia',
        'Tunisia', 'Japan', 'Ecuador', 'Kazakhstan', 'Croatia',
        'Costa Rica', 'Zambia', 'Moldova', 'Bolivia', 'Russia',
        'Bosnia-Herzegovina', 'Slovenia', 'Lithuania', 'Georgia',
        'Venezuela', 'Haiti', 'Central African Republic', 'Algeria',
        'Jamaica', 'The Gambia', 'Singapore', 'Macedonia', 'Estonia',
        'Albania', 'Korea, South', 'Czech Republic', 'United States',
        'South Africa', 'Madagascar', 'Panama', 'Indonesia', 'Angola',
        'Guinea-Bissau', 'Guinea', 'Uzbekistan', 'Luxembourg', 'Malta',
        'Mexico', 'Suriname', 'Korea, North', 'Belarus', 'Togo',
        'Slovakia', 'DR Congo', 'Iraq', 'Honduras', 'Burundi', 'Congo',
        'Wales', 'Kenya', 'Chile', 'Liberia', 'Gabon', 'Armenia', 'Peru',
        'Dominican Republic', 'Oman', "People's republic of the Congo",
        'Mozambique', 'Qatar', 'Egypt', 'St. Lucia', 'Faroe Islands',
        'Cyprus', 'Benin', 'Tajikistan', 'Netherlands Antilles',
        'Palestine', 'Serbia and Montenegro', 'Guadeloupe', 'Saudi Arabia',
        'Thailand', 'Trinidad and Tobago', 'China', 'Afghanistan',
        'Bermuda', 'Vietnam', 'French Guiana', 'Azerbaijan', 'El Salvador',
        'Syria', 'Somalia', 'Uganda', 'Macao', 'Tanzania', 'Ethiopia',
        'Jersey', 'Mauritania', 'Turkmenistan', 'San Marino', 'Mayotte',
        'Kyrgyzstan', 'Neukaledonien', 'Swaziland', 'Crimea',
        'Equatorial Guinea', 'Malaysia', 'Cuba', 'United Arab Emirates',
        'Liechtenstein', 'Sao Tome and Principe', 'Chad', 'Comoros',
        'Nicaragua', 'Rwanda', 'Latvia', 'Libya', 'Tahiti', 'Guatemala',
        'Dominica', 'Sudan', 'Pakistan', 'Bahrain', 'Malawi', 'Montserrat',
        'Kuwait', 'Isle of Man', 'Philippines', 'Djibouti', 'Curacao',
        'Niger', 'Papua New Guinea', 'Guernsey', 'Lebanon', 'India',
        'Andorra', 'Hongkong', 'Jordan', 'United Kingdom'], dtype=object),
 array(['Worms', 'Vratsa', 'Paderborn', ..., 'Vuzenica',
        'Enniscorthy, Wexford', 'Schiltigheim'], dtype=object),
 array([nan, 'right', 'left', 'both'], dtype=object))

In [34]:
players_df['foot'] = players_df['foot'].fillna('unknown')

In [35]:
# Dizionario per la mappatura dei nomi dei paesi
country_mapping = {
    "CSSR": "Czechoslovakia",
    "UdSSR": "Soviet Union",
    "East Germany (GDR)": "Germany",
    "United States": "USA",
    "United Kingdom": "UK"
}

# Applichiamo la mappatura al DataFrame
players_df['country_of_birth'] = players_df['country_of_birth'].replace(country_mapping)

# Verifichiamo nuovamente i valori unici per assicurarci che la mappatura sia stata applicata correttamente
sorted(players_df['country_of_birth'].unique())

['Afghanistan',
 'Albania',
 'Algeria',
 'Andorra',
 'Angola',
 'Argentina',
 'Armenia',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahrain',
 'Belarus',
 'Belgium',
 'Benin',
 'Bermuda',
 'Bolivia',
 'Bosnia-Herzegovina',
 'Brazil',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cameroon',
 'Canada',
 'Cape Verde',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo',
 'Costa Rica',
 "Cote d'Ivoire",
 'Crimea',
 'Croatia',
 'Cuba',
 'Curacao',
 'Cyprus',
 'Czech Republic',
 'Czechoslovakia',
 'DR Congo',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'England',
 'Equatorial Guinea',
 'Estonia',
 'Ethiopia',
 'Faroe Islands',
 'Finland',
 'France',
 'French Guiana',
 'Gabon',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Guadeloupe',
 'Guatemala',
 'Guernsey',
 'Guinea',
 'Guinea-Bissau',
 'Haiti',
 'Honduras',
 'Hongkong',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Isle of Man',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jersey',
 'Jordan',
 'Jugoslawien (SFR)',
 'Kazakhstan',
 'Kenya',
 'Korea, North',
 'Korea, South',
 'Kuwait',
 'Kyrgyzstan',
 'Latvia',
 'Lebanon',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Macao',
 'Macedonia',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Mali',
 'Malta',
 'Martinique',
 'Mauritania',
 'Mayotte',
 'Mexico',
 'Moldova',
 'Monaco',
 'Montserrat',
 'Morocco',
 'Mozambique',
 'Netherlands',
 'Netherlands Antilles',
 'Neukaledonien',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'Northern Ireland',
 'Norway',
 'Oman',
 'Pakistan',
 'Palestine',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 "People's republic of the Congo",
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Qatar',
 'Romania',
 'Russia',
 'Rwanda',
 'Réunion',
 'San Marino',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Scotland',
 'Senegal',
 'Serbia and Montenegro',
 'Sierra Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'Somalia',
 'South Africa',
 'Soviet Union',
 'Spain',
 'St. Lucia',
 'Sudan',
 'Suriname',
 'Swaziland',
 'Sweden',
 'Switzerland',
 'Syria',
 'Tahiti',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'The Gambia',
 'Togo',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'UK',
 'USA',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'Uruguay',
 'Uzbekistan',
 'Venezuela',
 'Vietnam',
 'Wales',
 'Yugoslavia (Republic)',
 'Zaire',
 'Zambia',
 'Zimbabwe',
 'unknown']

In [36]:
# Verifichiamo duplicati basati su 'name' e 'date_of_birth'
duplicate_players = players_df.duplicated(subset=['name', 'date_of_birth'], keep=False)
duplicated_data = players_df[duplicate_players].sort_values(by=['name', 'date_of_birth'])

# Visualizziamo i dati duplicati, se presenti
duplicated_data

,player_id,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,date_of_birth,sub_position,position,foot,height_in_cm,market_value_in_eur,contract_expiration_date,agent_name,current_club_domestic_competition_id,current_club_name
6680,461923,João Ricciulli,2022,2420,joao-ricciulli,unknown,Bissau,unknown,1999-10-10,Centre-Back,Defender,right,195.0,2.234721e+06,2023-06-30 00:00:00,unknown,PO1,Vitória Guimarães SC
19392,398057,João Ricciulli,2018,1038,joao-ricciulli,Guinea-Bissau,Bissau,Guinea-Bissau,1999-10-10,Left Winger,Attack,right,183.0,2.234721e+06,NaN,Evlon Sports & Mgmt,IT1,UC Sampdoria

In [37]:
# rimuovo il doppione
# Troviamo l'indice della riga con player_id 461923 e rimuoviamo quella riga
index_to_drop = players_df[players_df['player_id'] == 461923].index
players_df_dropped = players_df.drop(index_to_drop)

# Verifichiamo se la riga è stata rimossa
players_df_dropped[players_df_dropped['player_id'] == 461923]

Empty DataFrame
Columns: [player_id, name, last_season, current_club_id, player_code, country_of_birth, city_of_birth, country_of_citizenship, date_of_birth, sub_position, position, foot, height_in_cm, market_value_in_eur, contract_expiration_date, agent_name, current_club_domestic_competition_id, current_club_name]
Index: []

In [38]:
# converto i valori nelle colonne delle date nel formato datetime
players_df['date_of_birth'] = pd.to_datetime(players_df['date_of_birth'], errors='coerce')
players_df['contract_expiration_date'] = pd.to_datetime(players_df['contract_expiration_date'], errors='coerce')

In [39]:
missing_data = players_df.isnull().mean() * 100
missing_data

player_id                                0.000000
name                                     0.000000
last_season                              0.000000
current_club_id                          0.000000
player_code                              0.000000
country_of_birth                         0.000000
city_of_birth                            0.000000
country_of_citizenship                   0.000000
date_of_birth                            0.155105
sub_position                             0.000000
position                                 0.000000
foot                                     0.000000
height_in_cm                             0.000000
market_value_in_eur                      0.000000
contract_expiration_date                37.842387
agent_name                               0.000000
current_club_domestic_competition_id     0.000000
current_club_name                        0.000000
dtype: float64

In [40]:
players_df.to_csv('./data_cleaned/players.csv', index=False)

# Cleaning the dataset 'player_valuations'

In [41]:
player_valuations_df = pd.read_csv('./data/player_valuations.csv')
player_valuations_df.head()

,player_id,last_season,datetime,date,dateweek,market_value_in_eur,n,current_club_id,player_club_domestic_competition_id
0,3132,2013,2003-12-09 00:00:00,2003-12-09,2003-12-08,400000,1,126,TR1
1,6893,2012,2003-12-15 00:00:00,2003-12-15,2003-12-15,900000,1,984,GB1
2,10,2015,2004-10-04 00:00:00,2004-10-04,2004-10-04,7000000,1,398,IT1
3,26,2017,2004-10-04 00:00:00,2004-10-04,2004-10-04,1500000,1,16,L1
4,65,2015,2004-10-04 00:00:00,2004-10-04,2004-10-04,8000000,1,1091,GR1

In [42]:
# Rimozione delle colonne non necessarie e mantenimento solo della colonna 'date'
player_valuations_df = player_valuations_df.drop(columns=['datetime', 'n', 'dateweek'])
player_valuations_df.head()

,player_id,last_season,date,market_value_in_eur,current_club_id,player_club_domestic_competition_id
0,3132,2013,2003-12-09,400000,126,TR1
1,6893,2012,2003-12-15,900000,984,GB1
2,10,2015,2004-10-04,7000000,398,IT1
3,26,2017,2004-10-04,1500000,16,L1
4,65,2015,2004-10-04,8000000,1091,GR1

In [43]:
# Verifica dei valori mancanti nel dataset
missing_values = player_valuations_df.isnull().sum()

# Mostrare i valori mancanti per ogni colonna
missing_values

player_id                              0
last_season                            0
date                                   0
market_value_in_eur                    0
current_club_id                        0
player_club_domestic_competition_id    0
dtype: int64

In [44]:
# Verifica dei record duplicati nel dataset
duplicates_count = player_valuations_df.duplicated().sum()

# Mostrare il numero di duplicati trovati
duplicates_count

0

In [45]:
# Normalizzazione del formato delle date
player_valuations_df['date'] = pd.to_datetime(player_valuations_df['date'])

# Verifica dei tipi di dati attuali nel dataset
data_types = player_valuations_df.dtypes

# Mostrare i tipi di dati e il risultato della normalizzazione della colonna 'date'
data_types

player_id                                       int64
last_season                                     int64
date                                   datetime64[ns]
market_value_in_eur                             int64
current_club_id                                 int64
player_club_domestic_competition_id            object
dtype: object

In [46]:
player_valuations_df.to_csv('./data_cleaned/player_valuations.csv', index=False)

players_df.to_csv('./data_cleaned/players.csv', index=False)

# Cleaning the dataset ‘games’

In [47]:
# Caricare il dataset
games_df = pd.read_csv('./data/games.csv')
games_df.head()

,game_id,competition_id,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,...,stadium,attendance,referee,url,home_club_formation,away_club_formation,home_club_name,away_club_name,aggregate,competition_type
0,2222597,RU1,2012,6. Matchday,2012-08-25,3725,232,2,1,2.0,...,Akhmat-Arena,21700.0,Vladislav Bezborodov,https://www.transfermarkt.co.uk/terek-grozny_s...,NaN,NaN,RFK Akhmat Grozny,FK Spartak Moskva,2:1,domestic_league
1,2222627,RU1,2012,5. Matchday,2012-08-20,2696,4128,0,2,11.0,...,Metallurg,11400.0,Sergey Ivanov,https://www.transfermarkt.co.uk/krylya-sovetov...,NaN,NaN,PFK Krylya Sovetov Samara,Amkar Perm,0:2,domestic_league
2,2222658,RU1,2012,10. Matchday,2012-09-30,2410,121,0,2,2.0,...,Arena Khimki,12000.0,Sergey Karasev,https://www.transfermarkt.co.uk/cska-moscow_di...,NaN,NaN,PFK CSKA Moskva,FK Dinamo Moskva,0:2,domestic_league
3,2222664,RU1,2012,8. Matchday,2012-09-15,932,2698,1,0,5.0,...,RZD Arena,11408.0,Sergey Karasev,https://www.transfermarkt.co.uk/lokomotiv-mosc...,NaN,NaN,"Футбольный клуб ""Локомотив"" Москва",FC Rubin Kazan,1:0,domestic_league
4,2222683,RU1,2012,12. Matchday,2012-10-22,2696,12438,0,1,11.0,...,Metallurg,7534.0,Timur Arslanbekov,https://www.transfermarkt.co.uk/krylya-sovetov...,NaN,NaN,PFK Krylya Sovetov Samara,Volga Nizhniy Novgorod (- 2016),0:1,domestic_league

In [48]:
games_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65216 entries, 0 to 65215
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   game_id                 65216 non-null  int64
 1   competition_id          65216 non-null  object
 2   season                  65216 non-null  int64
 3   round                   65216 non-null  object
 4   date                    65216 non-null  object
 5   home_club_id            65216 non-null  int64
 6   away_club_id            65216 non-null  int64
 7   home_club_goals         65216 non-null  int64
 8   away_club_goals         65216 non-null  int64
 9   home_club_position      45762 non-null  float64
 10  away_club_position      45762 non-null  float64
 11  home_club_manager_name  64474 non-null  object
 12  away_club_manager_name  64474 non-null  object
 13  stadium                 65005 non-null  object
 14  attendance              55704 non-null  float64
 15  referee                 64622 non-null  object
 16  url                     65216 non-null  object
 17  home_club_formation     2869 non-null   object
 18  away_club_formation     2888 non-null   object
 19  home_club_name          53964 non-null  object
 20  away_club_name          55167 non-null  object
 21  aggregate               65216 non-null  object
 22  competition_type        65216 non-null  object
dtypes: float64(3), int64(6), object(14)
memory usage: 11.4+ MB

In [49]:
# Verifica dei valori mancanti nel dataset
missing_values = games_df.isnull().sum()

missing_values

game_id                       0
competition_id                0
season                        0
round                         0
date                          0
home_club_id                  0
away_club_id                  0
home_club_goals               0
away_club_goals               0
home_club_position        19454
away_club_position        19454
home_club_manager_name      742
away_club_manager_name      742
stadium                     211
attendance                 9512
referee                     594
url                           0
home_club_formation       62347
away_club_formation       62328
home_club_name            11252
away_club_name            10049
aggregate                     0
competition_type              0
dtype: int64

In [50]:
# Verifica dei record duplicati nel dataset
duplicates_count = games_df.duplicated().sum()

duplicates_count

0

In [51]:
# Normalizzazione del formato delle date
games_df['date'] = pd.to_datetime(games_df['date'])
games_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65216 entries, 0 to 65215
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   game_id                 65216 non-null  int64
 1   competition_id          65216 non-null  object
 2   season                  65216 non-null  int64
 3   round                   65216 non-null  object
 4   date                    65216 non-null  datetime64[ns]
 5   home_club_id            65216 non-null  int64
 6   away_club_id            65216 non-null  int64
 7   home_club_goals         65216 non-null  int64
 8   away_club_goals         65216 non-null  int64
 9   home_club_position      45762 non-null  float64
 10  away_club_position      45762 non-null  float64
 11  home_club_manager_name  64474 non-null  object
 12  away_club_manager_name  64474 non-null  object
 13  stadium                 65005 non-null  object
 14  attendance              55704 non-null  float64
 15  referee                 64622 non-null  object
 16  url                     65216 non-null  object
 17  home_club_formation     2869 non-null   object
 18  away_club_formation     2888 non-null   object
 19  home_club_name          53964 non-null  object
 20  away_club_name          55167 non-null  object
 21  aggregate               65216 non-null  object
 22  competition_type        65216 non-null  object
dtypes: datetime64[ns](1), float64(3), int64(6), object(13)
memory usage: 11.4+ MB

In [52]:
# Rimuoviamo le colonne specificate in quanto irrilevanti
games_df = games_df.drop(columns=['url', 'aggregate'])

games_df.head()

,game_id,competition_id,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,...,home_club_manager_name,away_club_manager_name,stadium,attendance,referee,home_club_formation,away_club_formation,home_club_name,away_club_name,competition_type
0,2222597,RU1,2012,6. Matchday,2012-08-25,3725,232,2,1,2.0,...,Stanislav Cherchesov,Unai Emery,Akhmat-Arena,21700.0,Vladislav Bezborodov,NaN,NaN,RFK Akhmat Grozny,FK Spartak Moskva,domestic_league
1,2222627,RU1,2012,5. Matchday,2012-08-20,2696,4128,0,2,11.0,...,Andrey Kobelev,Rustem Khuzin,Metallurg,11400.0,Sergey Ivanov,NaN,NaN,PFK Krylya Sovetov Samara,Amkar Perm,domestic_league
2,2222658,RU1,2012,10. Matchday,2012-09-30,2410,121,0,2,2.0,...,Leonid Slutski,Dan Petrescu,Arena Khimki,12000.0,Sergey Karasev,NaN,NaN,PFK CSKA Moskva,FK Dinamo Moskva,domestic_league
3,2222664,RU1,2012,8. Matchday,2012-09-15,932,2698,1,0,5.0,...,Slaven Bilic,Kurban Berdyev,RZD Arena,11408.0,Sergey Karasev,NaN,NaN,"Футбольный клуб ""Локомотив"" Москва",FC Rubin Kazan,domestic_league
4,2222683,RU1,2012,12. Matchday,2012-10-22,2696,12438,0,1,11.0,...,Andrey Kobelev,Gadzhi Gadzhiev,Metallurg,7534.0,Timur Arslanbekov,NaN,NaN,PFK Krylya Sovetov Samara,Volga Nizhniy Novgorod (- 2016),domestic_league

In [53]:
# Controlliamo per valori negativi nei goals
negative_goals = games_df[(games_df['home_club_goals'] < 0) | (games_df['away_club_goals'] < 0)]
# Controlliamo per valori negativi nelle positions
negative_positions = games_df[(games_df['home_club_position'] < 0) | (games_df['away_club_position'] < 0)]
# Controlliamo per valori negativi nelle attendance
negative_attendance = games_df[(games_df['attendance'] < 0)]

negative_goals.shape[0], negative_positions.shape[0], negative_attendance.shape[0]

(0, 0, 0)

In [54]:
# Controlliamo per partite in cui la squadra di casa e quella ospite sono le stesse
same_team_matches = games_df[games_df['home_club_id'] == games_df['away_club_id']]

same_team_matches.shape[0]

0

In [55]:
print(games_df.columns)

Index(['game_id', 'competition_id', 'season', 'round', 'date', 'home_club_id',
       'away_club_id', 'home_club_goals', 'away_club_goals',
       'home_club_position', 'away_club_position', 'home_club_manager_name',
       'away_club_manager_name', 'stadium', 'attendance', 'referee',
       'home_club_formation', 'away_club_formation', 'home_club_name',
       'away_club_name', 'competition_type'],
      dtype='object')

In [56]:
games_df['home_club_position'] = games_df['home_club_position'].fillna(-1)
games_df['away_club_position'] = games_df['away_club_position'].fillna(-1)
games_df['attendance'] = games_df['attendance'].fillna(-1)
games_df['stadium'] = games_df['stadium'].fillna('unknown')
games_df['home_club_manager_name'] = games_df['home_club_manager_name'].fillna('unknown')
games_df['away_club_manager_name'] = games_df['away_club_manager_name'].fillna('unknown')
games_df['referee'] = games_df['referee'].fillna('unknown')
games_df['home_club_formation'] = games_df['home_club_formation'].fillna('unknown')
games_df['away_club_formation'] = games_df['away_club_formation'].fillna('unknown') 
games_df['home_club_name'] = games_df['home_club_name'].fillna('unknown')
games_df['away_club_name'] = games_df['away_club_name'].fillna('unknown')

In [57]:
games_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65216 entries, 0 to 65215
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   game_id                 65216 non-null  int64
 1   competition_id          65216 non-null  object
 2   season                  65216 non-null  int64
 3   round                   65216 non-null  object
 4   date                    65216 non-null  datetime64[ns]
 5   home_club_id            65216 non-null  int64
 6   away_club_id            65216 non-null  int64
 7   home_club_goals         65216 non-null  int64
 8   away_club_goals         65216 non-null  int64
 9   home_club_position      65216 non-null  float64
 10  away_club_position      65216 non-null  float64
 11  home_club_manager_name  65216 non-null  object
 12  away_club_manager_name  65216 non-null  object
 13  stadium                 65216 non-null  object
 14  attendance              65216 non-null  float64
 15  referee                 65216 non-null  object
 16  home_club_formation     65216 non-null  object
 17  away_club_formation     65216 non-null  object
 18  home_club_name          65216 non-null  object
 19  away_club_name          65216 non-null  object
 20  competition_type        65216 non-null  object
dtypes: datetime64[ns](1), float64(3), int64(6), object(11)
memory usage: 10.4+ MB

In [58]:
games_df.to_csv('./data_cleaned/games.csv', index=False)

# Cleaning the dataset 'game_events'

In [59]:
# Caricare il dataset
game_events_df = pd.read_csv('./data/game_events.csv')
game_events_df.head()

,game_event_id,date,game_id,minute,type,club_id,player_id,description,player_in_id,player_assist_id
0,2f41da30c471492e7d4a984951671677,2012-08-05,2211607,77,Cards,610,4425,"1. Yellow card , Mass confrontation",NaN,NaN
1,a72f7186d132775f234d3e2f7bc0ed5b,2012-08-05,2211607,77,Cards,383,33210,"1. Yellow card , Mass confrontation",NaN,NaN
2,b2d721eaed4692a5c59a92323689ef18,2012-08-05,2211607,3,Goals,383,36500,", Header, 1. Tournament Goal Assist: , Corner,...",NaN,56416.0
3,aef768899cedac0c9a650980219075a2,2012-08-05,2211607,53,Goals,383,36500,", Right-footed shot, 2. Tournament Goal Assist...",NaN,146258.0
4,5d6d9533023057b6619ecd145a038bbe,2012-08-05,2211607,74,Substitutions,383,36500,", Not reported",49499.0,NaN

In [60]:
game_events_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 666558 entries, 0 to 666557
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   game_event_id     666558 non-null  object
 1   date              666558 non-null  object
 2   game_id           666558 non-null  int64
 3   minute            666558 non-null  int64
 4   type              666558 non-null  object
 5   club_id           666558 non-null  int64
 6   player_id         666558 non-null  int64
 7   description       330233 non-null  object
 8   player_in_id      421249 non-null  float64
 9   player_assist_id  30857 non-null   float64
dtypes: float64(2), int64(4), object(4)
memory usage: 50.9+ MB

In [61]:
# Verifica dei valori mancanti nel dataset
missing_values = game_events_df.isnull().sum()

missing_values

game_event_id            0
date                     0
game_id                  0
minute                   0
type                     0
club_id                  0
player_id                0
description         336325
player_in_id        245309
player_assist_id    635701
dtype: int64

In [62]:
# Normalizzazione del formato delle date
game_events_df['date'] = pd.to_datetime(game_events_df['date'])
game_events_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 666558 entries, 0 to 666557
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   game_event_id     666558 non-null  object
 1   date              666558 non-null  datetime64[ns]
 2   game_id           666558 non-null  int64
 3   minute            666558 non-null  int64
 4   type              666558 non-null  object
 5   club_id           666558 non-null  int64
 6   player_id         666558 non-null  int64
 7   description       330233 non-null  object
 8   player_in_id      421249 non-null  float64
 9   player_assist_id  30857 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(4), object(3)
memory usage: 50.9+ MB

In [63]:
# Controlliamo per valori sbagliati nei minute
valid_minutes = game_events_df['minute'].between(-1, 120).all()
# Nel dataset quando il valore di 'minute' è -1, significa che non si sa a quale minuto è avvenuto l'evento
valid_minutes

True

In [64]:
# Controlliamo che non ci siano eventi al minuto 0
game_events_df[game_events_df['minute']==0].shape[0]

0

In [65]:
# Verifica dei record duplicati nel dataset
duplicates_count = game_events_df.duplicated().sum()
duplicates_count

0

In [66]:
# Gestiamo i valori nulli delle colonne 'description', 'player_in_id', 'player_assist_id'
game_events_df['description'] = game_events_df['description'].fillna('unknown')
game_events_df['player_in_id'] = game_events_df['player_in_id'].fillna(-1)
game_events_df['player_assist_id'] = game_events_df['player_assist_id'].fillna(-1)

game_events_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 666558 entries, 0 to 666557
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   game_event_id     666558 non-null  object
 1   date              666558 non-null  datetime64[ns]
 2   game_id           666558 non-null  int64
 3   minute            666558 non-null  int64
 4   type              666558 non-null  object
 5   club_id           666558 non-null  int64
 6   player_id         666558 non-null  int64
 7   description       666558 non-null  object
 8   player_in_id      666558 non-null  float64
 9   player_assist_id  666558 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(4), object(3)
memory usage: 50.9+ MB

In [67]:
game_events_df.to_csv('./data_cleaned/game_events.csv', index=False)

# Cleaning the dataset 'appearances'

In [68]:
appearances_df = pd.read_csv('./data/appearances.csv')
appearances_df.head()

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,2231978_38004,2231978,38004,853,235,2012-07-03,Aurélien Joachim,CLQ,0,0,2,0,90
1,2233748_79232,2233748,79232,8841,2698,2012-07-05,Ruslan Abyshov,ELQ,0,0,0,0,90
2,2234413_42792,2234413,42792,6251,465,2012-07-05,Sander Puri,ELQ,0,0,0,0,45
3,2234418_73333,2234418,73333,1274,6646,2012-07-05,Vegar Hedenstad,ELQ,0,0,0,0,90
4,2234421_122011,2234421,122011,195,3008,2012-07-05,Markus Henriksen,ELQ,0,0,0,1,90

In [69]:
appearances_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1507351 entries, 0 to 1507350
Data columns (total 13 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   appearance_id           1507351 non-null  object
 1   game_id                 1507351 non-null  int64
 2   player_id               1507351 non-null  int64
 3   player_club_id          1507351 non-null  int64
 4   player_current_club_id  1507351 non-null  int64
 5   date                    1507351 non-null  object
 6   player_name             1507027 non-null  object
 7   competition_id          1507351 non-null  object
 8   yellow_cards            1507351 non-null  int64
 9   red_cards               1507351 non-null  int64
 10  goals                   1507351 non-null  int64
 11  assists                 1507351 non-null  int64
 12  minutes_played          1507351 non-null  int64
dtypes: int64(9), object(4)
memory usage: 149.5+ MB

In [70]:
# calcoliamo i valori mancanti in pecentuale per colonna
missing_data = appearances_df.isnull().mean() * 100
missing_data.sort_values(ascending=False)

player_name               0.021495
appearance_id             0.000000
game_id                   0.000000
player_id                 0.000000
player_club_id            0.000000
player_current_club_id    0.000000
date                      0.000000
competition_id            0.000000
yellow_cards              0.000000
red_cards                 0.000000
goals                     0.000000
assists                   0.000000
minutes_played            0.000000
dtype: float64

In [71]:
appearances_df['player_name'].isna().sum()

324

In [72]:
# Trova gli ID dei giocatori con il nome 'unknown' in appearances_df
unknown_players = appearances_df[appearances_df['player_name'].isna()]

# Visualizza gli ID di questi giocatori
print("Player IDs with 'unknown' names:")
print(unknown_players['player_id'])

# Cerca questi ID in un altro dataframe, players_df, per ottenere più informazioni
corresponding_players = players_df[players_df['player_id'].isin(unknown_players['player_id'])]

# Visualizza le informazioni trovate in players_df
print("Details from players_df for unknown player names:")
print(corresponding_players)

Player IDs with 'unknown' names:
268984     14280
268990    192599
268991    194603
268996     33235
268997     35246
           ...
597505    255495
599128    255495
601750    255495
604708    255495
804128    380365
Name: player_id, Length: 324, dtype: int64
Details from players_df for unknown player names:
Empty DataFrame
Columns: [player_id, name, last_season, current_club_id, player_code, country_of_birth, city_of_birth, country_of_citizenship, date_of_birth, sub_position, position, foot, height_in_cm, market_value_in_eur, contract_expiration_date, agent_name, current_club_domestic_competition_id, current_club_name]
Index: []

In [73]:
# rimuovo le righe con player_name vuoto
appearances_df = appearances_df.dropna(subset=['player_name'])
appearances_df['player_name'].isna().sum()

0

In [74]:
appearances_df['date'] = pd.to_datetime(appearances_df['date'], errors='coerce')

In [75]:
# Verifica delle righe duplicate nel DataFrame
duplicates = appearances_df.duplicated()

# Conteggio delle righe duplicate
num_duplicates = duplicates.sum()
num_duplicates

0

In [76]:
neg_goal = (appearances_df['goals'] < 0).any()
neg_assists = (appearances_df['assists'] < 0).any()
neg_ycard = (appearances_df['yellow_cards'] < 0).any()
neg_rcard = (appearances_df['red_cards'] < 0).any()
neg_min_played = (appearances_df['minutes_played'] < 0).any()
invalid_ycard = (appearances_df['yellow_cards'] > 2).any()
invalid_rcard = (appearances_df['red_cards'] > 1).any()
invalid_min_played = (appearances_df['minutes_played'] > 120).any()

print("Negative Goals:", neg_goal)
print("Negative Assists:", neg_assists)
print("Negative Yellow Cards:", neg_ycard)
print("Negative Red Cards:", neg_rcard)
print("Negative Minutes Played:", neg_min_played)
print("Invalid Yellow Cards:", invalid_ycard)
print("Invalid Red Cards:", invalid_rcard)
print("Invalid Minutes Played:", invalid_min_played)

Negative Goals: False
Negative Assists: False
Negative Yellow Cards: False
Negative Red Cards: False
Negative Minutes Played: False
Invalid Yellow Cards: False
Invalid Red Cards: False
Invalid Minutes Played: False

In [77]:
appearances_df.to_csv('./data_cleaned/appearances.csv', index=False)

# Cleaning the dataset ‘competitions’

In [78]:
# Caricamento del dataset
competitions_df = pd.read_csv('./data/competitions.csv')
competitions_df.head()

,competition_id,competition_code,name,sub_type,type,country_id,country_name,domestic_league_code,confederation,url
0,CIT,italy-cup,italy-cup,domestic_cup,domestic_cup,75,Italy,IT1,europa,https://www.transfermarkt.co.uk/italy-cup/star...
1,NLSC,johan-cruijff-schaal,johan-cruijff-schaal,domestic_super_cup,other,122,Netherlands,NL1,europa,https://www.transfermarkt.co.uk/johan-cruijff-...
2,GRP,kypello-elladas,kypello-elladas,domestic_cup,domestic_cup,56,Greece,GR1,europa,https://www.transfermarkt.co.uk/kypello-ellada...
3,POSU,supertaca-candido-de-oliveira,supertaca-candido-de-oliveira,domestic_super_cup,other,136,Portugal,PO1,europa,https://www.transfermarkt.co.uk/supertaca-cand...
4,RUSS,russian-super-cup,russian-super-cup,domestic_super_cup,other,141,Russia,RU1,europa,https://www.transfermarkt.co.uk/russian-super-...

In [79]:
competitions_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   competition_id        43 non-null     object
 1   competition_code      43 non-null     object
 2   name                  43 non-null     object
 3   sub_type              43 non-null     object
 4   type                  43 non-null     object
 5   country_id            43 non-null     int64
 6   country_name          36 non-null     object
 7   domestic_league_code  36 non-null     object
 8   confederation         43 non-null     object
 9   url                   43 non-null     object
dtypes: int64(1), object(9)
memory usage: 3.5+ KB

In [80]:
# Rimozione colonne irrilevanti
competitions_df = competitions_df.drop(columns=['url'])

In [81]:
competitions_df.head()

,competition_id,competition_code,name,sub_type,type,country_id,country_name,domestic_league_code,confederation
0,CIT,italy-cup,italy-cup,domestic_cup,domestic_cup,75,Italy,IT1,europa
1,NLSC,johan-cruijff-schaal,johan-cruijff-schaal,domestic_super_cup,other,122,Netherlands,NL1,europa
2,GRP,kypello-elladas,kypello-elladas,domestic_cup,domestic_cup,56,Greece,GR1,europa
3,POSU,supertaca-candido-de-oliveira,supertaca-candido-de-oliveira,domestic_super_cup,other,136,Portugal,PO1,europa
4,RUSS,russian-super-cup,russian-super-cup,domestic_super_cup,other,141,Russia,RU1,europa

In [82]:
# Controllo delle colonne che hanno valori mancanti
missing_values_count = competitions_df.isnull().sum()
missing_values_count[missing_values_count > 0]

country_name            7
domestic_league_code    7
dtype: int64

In [83]:
# Sostituzione dei valori mancanti con 'not available' per la colonna 'country'
competitions_df['country_name'] = competitions_df['country_name'].fillna('european_continent')

# Sostituzione dei valori mancanti con '-1' per la colonna 'domestic_league_code'
competitions_df['domestic_league_code'] = competitions_df['domestic_league_code'].fillna(-1)

In [84]:
# Verifica dei record duplicati nel dataset
duplicates_count = competitions_df.duplicated().sum()
duplicates_count

0

In [85]:
competitions_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   competition_id        43 non-null     object
 1   competition_code      43 non-null     object
 2   name                  43 non-null     object
 3   sub_type              43 non-null     object
 4   type                  43 non-null     object
 5   country_id            43 non-null     int64
 6   country_name          43 non-null     object
 7   domestic_league_code  43 non-null     object
 8   confederation         43 non-null     object
dtypes: int64(1), object(8)
memory usage: 3.2+ KB

In [86]:
competitions_df.to_csv('./data_cleaned/competitions.csv', index=False)

# Cleaning the dataset 'game_lineups'

In [87]:
# Caricamento del dataset
game_lineups_df = pd.read_csv('./data/game_lineups.csv')
game_lineups_df.head()

,game_lineups_id,game_id,club_id,type,number,player_id,player_name,team_captain,position
0,77b0f371923e0c8bdf050a1e269faaac,3606208,338,starting_lineup,89,419061,Vladyslav Supryaga,0,Centre-Forward
1,cb6eeedb9f728570615d37b6fe7facaf,3606208,338,starting_lineup,10,368611,Mykola Shaparenko,0,Central Midfield
2,8e63d5f47aac2bdb0e54f5481986e104,3606208,338,starting_lineup,5,124182,Sergiy Sydorchuk,1,Defensive Midfield
3,ea4a96d8be410f2d646cf095c4faae7f,3606208,338,starting_lineup,94,181118,Tomasz Kedziora,0,Right-Back
4,e6abe553801b09bc623c3deb96acba17,3606208,338,starting_lineup,16,404842,Vitaliy Mykolenko,0,Left-Back

In [88]:
game_lineups_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119133 entries, 0 to 119132
Data columns (total 9 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   game_lineups_id  119133 non-null  object
 1   game_id          119133 non-null  int64
 2   club_id          119133 non-null  int64
 3   type             119133 non-null  object
 4   number           119133 non-null  object
 5   player_id        119133 non-null  int64
 6   player_name      119133 non-null  object
 7   team_captain     119133 non-null  int64
 8   position         119133 non-null  object
dtypes: int64(4), object(5)
memory usage: 8.2+ MB

In [89]:
# Conversione della colonna 'number' da stringa a numerico, gestendo valori non numerici e mancanti
game_lineups_df['number'] = pd.to_numeric(game_lineups_df['number'], errors='coerce')

# Verificare la presenza di valori mancanti nelle colonne
missing_values = game_lineups_df.isnull().sum()

# Ricerca di righe duplicate
duplicate_rows = game_lineups_df.duplicated().sum()

missing_values, duplicate_rows

(game_lineups_id       0
 game_id               0
 club_id               0
 type                  0
 number             1355
 player_id             0
 player_name           0
 team_captain          0
 position              0
 dtype: int64,
 0)

In [90]:
# Sostituire i valori NaN nella colonna 'number' con -1
game_lineups_df['number'] = game_lineups_df['number'].fillna(-1)

# Verificare la modifica
game_lineups_df['number'].isnull().sum()

0

In [91]:
# Verificare la presenza di valori negativi nella colonna 'number' diversi da -1
negative_values_except_minus_one = game_lineups_df[game_lineups_df['number'] <= 0]
negative_values_except_minus_one = negative_values_except_minus_one[negative_values_except_minus_one['number'] != -1]

# Verificare la presenza di valori maggiori o uguali a 100 nella colonna 'number'
values_100_or_more = game_lineups_df[game_lineups_df['number'] >= 100]

negative_values_except_minus_one.shape[0], values_100_or_more.shape[0]

(0, 0)

In [92]:
# Verificare la presenza di valori diversi da 0 e 1 nella colonna 'team_captain'
invalid_team_captain_values = game_lineups_df[~game_lineups_df['team_captain'].isin([0, 1])]

invalid_team_captain_values.shape[0]

0

In [95]:
# Verificare la presenza di valori diversi da "starting_lineup" e "substitutes" nella colonna 'type'
invalid_type_values = game_lineups_df[~game_lineups_df['type'].isin(["starting_lineup", "substitutes"])]

invalid_type_values.shape[0]

0

In [94]:
game_lineups_df.to_csv('./data_cleaned/game_lineups.csv', index=False)